export const SIGNIN_TEXT = "Sign in!";
export const SIGNUP_TEXT = "Sign up!"
export const SIGNOUT_TEXT = "Sign out!";
export const PROFILE_TEXT = "Profile";
export const MY_ORDERS_TEXT = "My Orders";
export const CART_TEXT = "Cart";
export const CURRENCY_DOLLAR = "$";
export const SIGNIN_REDIRECTION_LINK_TEXT = "Already have an account? Sign In"
export const SIGNUP_REDIRECTION_LINK_TEXT = "You don't have an account? Sign Up"
export const WEBSITE_TITLE = "FashionHub"
export const COPYRIGHT = "Copyright © "