export const SIGNIN_TEXT = "Sign in!";
export const SIGNUP_TEXT = "Sign up!"
export const SIGNOUT_TEXT = "Sign out!";
export const PROFILE_TEXT = "Profile";
export const MY_ORDERS_TEXT = "My Orders";
export const CART_TEXT = "Cart";
export const CURRENCY_DOLLAR = "$";
export const SIGNIN_REDIRECTION_LINK_TEXT = "Already have an account? Sign In"
export const SIGNUP_REDIRECTION_LINK_TEXT = "You don't have an account? Sign Up"
export const WEBSITE_TITLE = "FashionHub"
export const COPYRIGHT = "Copyright © "
export const FEATURED_PRODUCTS_TEXT = 'Featured Products';
export const PRODUCTS_NOT_FOUND_MESSAGE = "Sorry, the requested products could not be found.";
export const ERROR_TITLE = "Error!"
export const QUANTITY_TEXT = "Quantity in cart";
export const TOTAL_REVIEWS = "Reviews";
export const PRICE_TEXT = "Price";
export const DESCRIPTION_TEXT = "Description"
export const IN_STOCK_TEXT = "In Stock"
export const NOT_IN_STOCK_TEXT = "Not In Stock"
export const ADD_TO_CART_TEXT = "Add to Cart"
export const STATUS = "Status"
export const SIGN_IN_ERROR = "Sign in first !"
export const SHIPPING_ADDRESS = "Shipping Address"
export const PAYMENT_METHOD_TEXT = "Payment Method"
export const CONTINUE_TEXT = "Continue"