export const SIGNIN_TEXT = "Signin!";
export const SIGNUP_TEXT = "Signup!"
export const SIGNOUT_TEXT = "Sign out!";
export const PROFILE_TEXT = "Profile";
export const MY_ORDERS_TEXT = "My Orders";
export const CART_TEXT = "Cart";
export const CURRENCY_DOLLAR = "$";
export const FEATURED_PRODUCTS_TEXT = 'Featured Products';
export const PRODUCTS_NOT_FOUND_MESSAGE = "Sorry, the requested products could not be found.";
export const ERROR_TITLE = "Error!"
export const QUANTITY_TEXT = "Quantity in cart";
export const TOTAL_REVIEWS = "Reviews";
